### ISSUE TITLE
Use JSON schema to describe request/response payloads

### ISSUE THREAD

**Issue by cdanger** [openid/authzen#109]
What about using JSON schema to describe the API request/response payloads? e.g. Authorization API 

That would help with request validation, code generation, and improving/simplifying the API description.

**Comment by ogazitt** [comment]
The maintainers discussed and we strongly agree with this observation. The new version (1_0_01) makes it easier to write a meaningful JSON schema for the payloads (not to mention create a protobuf contract/gRPC binding).
