### ISSUE TITLE
Fix action names in interop scenario

### ISSUE THREAD

**Issue by cdanger** [openid/authzen#111]
The action names in the [description of scenario](../blob/main/interop/authzen-interop-website/docs/scenarios/todo.md) all have a `can_` prefix, e.g. `can_read_user`, which is cumbersome and not really appropriate for an action name. Why not simplify:  `read_user`, `read_todos`, `create_todo`, etc. ?

**Comment by ogazitt** [comment]
`can_` is a common convention for permission names in many ReBAC systems. At any rate, it ain't broken, so not worth having to make a breaking change and address in 14 interoperable implementations.

**Comment by cdanger** [comment]
A bit late now for sure. But if there is another round of interop tests, I'd reconsider it, and also for the future standard itself. It seems I'm not the only one confused by this convention: #123 . At least, there is no such convention in RBAC/ABAC (and this scenario is a textbook case for RBAC in particular). I checked examples of two ReBAC systems by curiosity: [Oso](https://www.osohq.com/docs/guides/relationship-based-access-control-rebac),  or [permit.io (example based on Google Zanzibar)](https://docs.permit.io/modeling/google-drive/#define-resources-and-roles). I don't see the `can_` prefix in permissions.
Could you cite a ReBAC document or with such convention? Maybe that would help me understand.

Maybe there is a confusion between permission and action in this case. So just to clarify, I was talking about _action_ names in the request payloads. I can agree to have a permission called `can_read_todo` but then I would differentiate it from the _action_ name itself which is a sub-item of the permission here, and can still be called `read` or `read_todo`. 
So you can say something like **the permission `can_read_todo` corresponds to the tuple { action: 'read', resource: any with type 'todo'}.** Then use the action name `read` in the actual authorization requests (and resource type attribute set to 'todo').
