### ISSUE TITLE
Remove "can_" from common actions

### ISSUE THREAD

**Issue by johakoch** [openid/authzen#123]
The five common actions defined in [5.3.1. Common Action Values](https://openid.github.io/authzen/#section-5.3.1) have a "can_" prefix. Why? [5.3. Action](https://openid.github.io/authzen/#section-5.3) says:

> An Action is the type of access that the requester intends to perform.

I'd say, the "type of access that the requester intends to perform" is "access", "create", "read", "update" or "delete"; not "_to be able to_ access, ...".

I don't know about possible previous discussions about this, so please bear with me.

To me, "can_access" sounds more like a permission to perform the action itself. But the _can_ is for the whole tuple (like `can(<subject>, <action>, <resource>, <context>)`), isn't it?

**Comment by ogazitt** [comment]
The "can_" prefix was somewhat intentional, and tends to correspond to the convention of how permissions are named as distinct from relations in many ReBAC systems.  So, a subject (`user:johakoch`) may be a `viewer` on a resource (`document:authzen-spec`), and the `viewer` relation grants the `can_read` permission.

**Comment by johakoch** [comment]
Hi @ogazitt So you view the _action_ to be the same as the _permission_ to perform the action?

**Comment by johakoch** [comment]
See https://github.com/openid/authzen/issues/154

**Comment by randomstuff** [comment]
Woops I tried to find this but failed …

Semantically, it feels weird to have an action which is `can_read`. I would expect the action to be `read`.

Of course we are talking about checking whether I can read the resource but the action I'm checking is "read".
