### ISSUE TITLE
Formatting of bullet list in 7.1.3 is broken

### ISSUE THREAD

**Issue by jogu** [openid/authzen#149]
The formatting of the bullet list here is broken:

https://openid.net/specs/authorization-api-1_0-01.html#section-7.1.3

<img width="891" alt="Screenshot 2024-09-19 at 08 14 43" src="https://github.com/user-attachments/assets/3fdcf7ee-7bc2-4dd8-8ebf-7c7e7f07fd78">

(Experience suggests it's probably a missing blank link before or after the list, but there could be another cause)

**Comment by jogu** [comment]
(FYI I'm covered by Authlete's "all working groups" contribution agreement.)

**Comment by ogazitt** [comment]
resolved by https://github.com/openid/authzen/pull/178

**Comment by ogazitt** [comment]
https://openid.github.io/authzen/authorization-api-1_0_02.html#name-error-responses
