### ISSUE TITLE
Discussion: Is providing reason reasonable?

### ISSUE THREAD

**Issue by independentid** [openid/authzen#163]
In a de-coupled PDP/PEP environment, it is difficult to conceive how a PDP can convey `reason` (admin or user) values except in the case of specific "deny" policies.

If a PDP system is default deny unless permitted, then most responses can have no reason because no permission was matched.

What other information could or should be provided (e.g. count of policies reviewed)?

If it is useful to give a reason for denial, is it useful to give reason for permission (e.g. which policy permitted the action)?

**Comment by ogazitt** [comment]
Example of a reason code: if the authorizer fails to load a referenced subject or resource, it could return an `HTTP 200`, `decision: false`, and a `reason` that relates to a `404` error (subject or object not found).

**Comment by davidjbrossard** [comment]
In some policy-based systems, it's possible to define a blanket reason (obligation/advice in ALFA) that will apply if none of the policies apply. Reasons are not mandatory by the way so you can choose to not return any.
