### ISSUE TITLE
AUTHZEN_PDP_URL for authzen-todo-backend

### ISSUE THREAD

**Issue by kg0r0** [openid/authzen#181]
As per the [README](https://github.com/openid/authzen/blob/f924fe41b291444150c797faeb481b630ad2d7e7/interop/authzen-todo-backend/README.md?plain=1#L15), it seems that AuthZEN requests are sent to `${AUTHZEN_PDP_URL}/access/v1/evaluations`.
However, it seems that those are actually sent to `${AUTHZEN_PDP_URL}/access/v1/evaluation` as well as `${AUTHZEN_PDP_URL}/access/v1/evaluations`.
https://github.com/openid/authzen/blob/f924fe41b291444150c797faeb481b630ad2d7e7/interop/authzen-todo-backend/src/auth.ts#L107

https://github.com/openid/authzen/blob/f924fe41b291444150c797faeb481b630ad2d7e7/interop/authzen-todo-backend/src/auth.ts#L149

As per [the latest spec](https://openid.github.io/authzen/authorization-api-1_1_01),   it seems that two endpoints (`/access/v1/evaluation` and `/access/v1/evaluation`) will be used. So, it may be better to update the description.

**Comment by ogazitt** [comment]
https://github.com/openid/authzen/pull/187
