### ISSUE TITLE
rename "Resource Query" -> "Resource Lookup Query"

### ISSUE THREAD

**Issue by tr33** [openid/authzen#49]
[Resource Query](https://openid.github.io/authzen/#name-resource-query) currently defines a lookup action on resources.

For clarification, "Resource Query" should be renamed to "Resource Lookup Query".

Other actions (like "update" or "delete") may be subject to further definition?

**Comment by baboulebou** [comment]
It's actually called: "Resource Search Request". 
Check here: https://github.com/openid/authzen/blob/main/authorization-api-1_0.md#resource-search-request

**Comment by ggebel** [comment]
See section 3.13.1
