### ISSUE TITLE
Add "Subject Lookup Query"

### ISSUE THREAD

**Issue by tr33** [openid/authzen#51]
The draft currently defines a [Resource Query](https://github.com/openid/authzen/blob/main/authorization-api-1_0.md#resource-query-resource-query) API to lookup whether a subject can access a specific resource.

There should also be a complementary query to lookup which subjects have access a given resource.
Like "_which _users_ (subjects) can _read_ the document 'xyz'_?"
(whereas '_user_' is a _subject_ of type 'user' and "_document 'xyz'_" is a _resource_ of type "document" and id 'xyz')

Proposed wording
```
## Subject Lookup Query

Perform a lookup of all subjects of a particular kind which have permissions to a certain resource. This is the complementary operation of 'Resource Lookup Query'.
Lookup subjects can be used in form of a question like "which subjects of type '_user_' have '_read_' permission on the object of 'document' and 'xyz'?"
```

mandatory input parameters should be
 - resource definition (resource type or other criteria)
 - permission (or relation?)
 - subject criteria (type definition like "user" or "devices" or whichever type a subject may have)

**Comment by baboulebou** [comment]
The "Resource Search" and "Subject Search" APIs are already provided and part of the initial draft. Please check the draft again.

**Comment by ggebel** [comment]
This topic is already included in the draft spec
